# This is a config for E2B sandbox template.
# You can use template ID (ycjhvwtqqs5ij66gevjt) or template name (pitchdeck-ai) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("pitchdeck-ai") # Sync sandbox
# sandbox = await AsyncSandbox.create("pitchdeck-ai") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('pitchdeck-ai')

team_id = "cac4d450-eb97-4fca-8c7f-bccae715fa57"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "pitchdeck-ai"
template_id = "ycjhvwtqqs5ij66gevjt"
